import { conf as cppConfiguration, language as cppTokens } from 'monaco-editor/esm/vs/basic-languages/cpp/cpp.js'
import { conf as csharpConfiguration, language as csharpTokens } from 'monaco-editor/esm/vs/basic-languages/csharp/csharp.js'
import { conf as fsharpConfiguration, language as fsharpTokens } from 'monaco-editor/esm/vs/basic-languages/fsharp/fsharp.js'
import { conf as javaConfiguration, language as javaTokens } from 'monaco-editor/esm/vs/basic-languages/java/java.js'
import { conf as phpConfiguration, language as phpTokens } from 'monaco-editor/esm/vs/basic-languages/php/php.js'
import { conf as visualBasicConfiguration, language as visualBasicTokens } from 'monaco-editor/esm/vs/basic-languages/vb/vb.js'
import { ilKeywords, ilOpcodes, ilPrimitiveTypes, ilStandaloneAssemblyIdentityPattern } from '../editor/ilLanguageTokens'
import * as monaco from '../editor/monacoCore'

let registered = false

export const sourceEditorTheme = 'sharplabnext-light'

const registeredLanguageIds: Readonly<Record<string, string>> = {
  csharp: 'csharp',
  'visual-basic': 'visual-basic',
  fsharp: 'fsharp',
  gsharp: 'gsharp',
  php: 'php',
  cppcli: 'cpp',
  jsharp: 'jsharp',
  il: 'il',
  asm: 'asm',
  minilang: 'minilang',
}

const modernCsharpKeywords = [
  'and',
  'bool',
  'byte',
  'char',
  'decimal',
  'double',
  'file',
  'float',
  'init',
  'int',
  'long',
  'nint',
  'not',
  'nuint',
  'object',
  'or',
  'record',
  'required',
  'sbyte',
  'scoped',
  'short',
  'string',
  'uint',
  'ulong',
  'unmanaged',
  'ushort',
  'void',
  'with',
] as const

const csharpAttributeTargets = /(?:assembly|module|return|method|field|property|event|type|param)/
const csharpAttributeStart = /^(\s*)(\[)(?=\s*(?:(?:assembly|module|return|method|field|property|event|type|param)\s*:\s*)?(?:(?:global\s*::\s*)?@?[A-Za-z_]\w*))/
const csharpNextAttribute = /(\])(\s*)(\[)(?=\s*(?:(?:assembly|module|return|method|field|property|event|type|param)\s*:\s*)?(?:(?:global\s*::\s*)?@?[A-Za-z_]\w*))/

export const csharpVsTokens: monaco.languages.IMonarchLanguage = {
  ...csharpTokens,
  keywords: [...new Set([...(csharpTokens.keywords ?? []), ...modernCsharpKeywords])],
  csharpAttributeTargets,
  tokenizer: {
    ...csharpTokens.tokenizer,
    root: [
      [csharpAttributeStart, ['', { token: 'delimiter.square', next: '@attribute' }]],
      [/(class|struct|interface|enum|record)(\s+)([A-Za-z_]\w*)/, ['keyword', 'white', 'type.identifier']],
      [
        /@?[A-Za-z_]\w*(?=\s*\()/,
        {
          cases: {
            '@keywords': { token: 'keyword.$0', next: '@qualified' },
            '@default': { token: 'function', next: '@qualified' },
          },
        },
      ],
      [/[A-Z][A-Za-z0-9_]*(?=\s*(?:\.|<|\[|\?|\s+[A-Za-z_]\w*))/, 'type.identifier'],
      ...(csharpTokens.tokenizer.root ?? []),
    ],
    attribute: [
      { include: '@whitespace' },
      [/(@csharpAttributeTargets)(\s*)(:)/, ['keyword', '', 'delimiter']],
      [/(global)(\s*)(::)/, ['keyword', '', 'delimiter']],
      [/@?[A-Za-z_]\w*(?=\s*(?:\.|::))/, 'namespace'],
      [/@?[A-Za-z_]\w*/, { token: 'type.identifier', switchTo: '@attributeAfterName' }],
      [csharpNextAttribute, ['delimiter.square', '', { token: 'delimiter.square', switchTo: '@attribute' }]],
      [/\]/, 'delimiter.square', '@pop'],
    ],
    attributeAfterName: [
      { include: '@whitespace' },
      [csharpNextAttribute, ['delimiter.square', '', { token: 'delimiter.square', switchTo: '@attribute' }]],
      [/\]/, 'delimiter.square', '@pop'],
      [/\(/, { token: 'delimiter.parenthesis', switchTo: '@attributeArguments' }],
      [/,/, { token: 'delimiter', switchTo: '@attribute' }],
      { include: '@root' },
    ],
    attributeArguments: [[/\[/, 'delimiter.square', '@attributeArray'], [/\]/, 'delimiter.square', '@pop'], { include: '@root' }],
    attributeArray: [[/\[/, 'delimiter.square', '@push'], [/\]/, 'delimiter.square', '@pop'], { include: '@root' }],
  },
}

export function registerSourceLanguages(): void {
  if (registered) return
  registered = true

  registerLanguage('csharp', ['.cs'], ['C#', 'csharp'], csharpConfiguration, csharpVsTokens)
  registerLanguage('cpp', ['.cpp', '.cc', '.cxx'], ['C++/CLI', 'cpp'], cppConfiguration, cppCliTokens)
  registerLanguage('fsharp', ['.fs', '.fsx'], ['F#', 'fsharp'], fsharpConfiguration, fsharpTokens)
  registerLanguage('jsharp', ['.jsl'], ['J#', 'jsharp'], javaConfiguration, {
    ...javaTokens,
    tokenPostfix: '.jsharp',
  })
  registerLanguage('javascript', ['.js'], ['JavaScript', 'javascript'], javascriptConfiguration, javascriptTokens)
  registerLanguage('visual-basic', ['.vb'], ['Visual Basic', 'visual-basic'], visualBasicConfiguration, visualBasicTokens)
  registerLanguage('gsharp', ['.gs'], ['G#', 'gsharp'], gsharpConfiguration, gsharpTokens)
  registerLanguage('php', ['.php'], ['PHP', 'php'], phpConfiguration, phpTokens)
  registerLanguage('il', ['.il'], ['IL', 'il'], ilConfiguration, ilTokens)
  registerLanguage('asm', [], ['Assembly', 'asm'], assemblyConfiguration, assemblyTokens)
  registerLanguage('minilang', ['.mini'], ['MiniLang', 'minilang'], minilangConfiguration, minilangTokens)

  monaco.editor.defineTheme(sourceEditorTheme, {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'identifier', foreground: '000000' },
      { token: 'namespace', foreground: '000000' },
      { token: 'type', foreground: '2B91AF' },
      { token: 'type.identifier', foreground: '2B91AF' },
      { token: 'class', foreground: '2B91AF' },
      { token: 'struct', foreground: '2B91AF' },
      { token: 'interface', foreground: '2B91AF' },
      { token: 'enum', foreground: '2B91AF' },
      { token: 'delegate', foreground: '2B91AF' },
      { token: 'typeParameter', foreground: '2B91AF' },
      { token: 'method', foreground: '795E26' },
      { token: 'function', foreground: '795E26' },
      { token: 'property', foreground: '001080' },
      { token: 'field', foreground: '001080' },
      { token: 'event', foreground: '001080' },
      { token: 'enumMember', foreground: '0070C1' },
      { token: 'parameter', foreground: '001080' },
      { token: 'variable', foreground: '001080' },
      { token: 'label', foreground: 'AF00DB' },
      { token: 'macro', foreground: 'AF00DB' },
      { token: 'keyword', foreground: '0000FF' },
      { token: 'modifier', foreground: '0000FF' },
      { token: 'string', foreground: 'A31515' },
      { token: 'string.escape', foreground: 'EE0000' },
      { token: 'stringEscapeCharacter', foreground: 'EE0000' },
      { token: 'number', foreground: '098658' },
      { token: 'comment', foreground: '008000' },
      { token: 'regexp', foreground: '811F3F' },
      { token: 'operator', foreground: '000000' },
      { token: 'delimiter', foreground: '000000' },
    ],
    colors: {
      'editor.background': '#FFFFFF',
      'editor.foreground': '#1F2328',
      'editor.lineHighlightBackground': '#F5F8FC',
      'editor.selectionBackground': '#ADD6FF',
      'editor.inactiveSelectionBackground': '#D8E2EC',
      'editorCursor.foreground': '#1F6FEB',
      'editorLineNumber.foreground': '#68717D',
      'editorLineNumber.activeForeground': '#1F2328',
      'editorIndentGuide.background1': '#E8ECF1',
      'editorIndentGuide.activeBackground1': '#B8C3D1',
      'editorSuggestWidget.background': '#FFFFFF',
      'editorSuggestWidget.border': '#B8C3D1',
      'editorSuggestWidget.foreground': '#1E1E1E',
      'editorSuggestWidget.highlightForeground': '#005FB8',
      'editorSuggestWidget.selectedBackground': '#0067C0',
      'editorSuggestWidget.selectedForeground': '#FFFFFF',
      'editorSuggestWidget.selectedIconForeground': '#FFFFFF',
      'editorSuggestWidget.focusHighlightForeground': '#FFFFFF',
      'symbolIcon.keywordForeground': '#0000FF',
      'symbolIcon.classForeground': '#2B91AF',
      'symbolIcon.interfaceForeground': '#2B91AF',
      'symbolIcon.structForeground': '#2B91AF',
      'symbolIcon.enumForeground': '#2B91AF',
      'symbolIcon.methodForeground': '#795E26',
      'symbolIcon.functionForeground': '#795E26',
      'symbolIcon.propertyForeground': '#001080',
      'symbolIcon.variableForeground': '#001080',
      'symbolIcon.fieldForeground': '#001080',
    },
  })
}

function registerLanguage(id: string, extensions: string[], aliases: string[], configuration: monaco.languages.LanguageConfiguration, tokens: monaco.languages.IMonarchLanguage): void {
  if (!monaco.languages.getLanguages().some((language) => language.id === id)) {
    monaco.languages.register({ id, extensions, aliases })
  }
  monaco.languages.setLanguageConfiguration(id, configuration)
  monaco.languages.setMonarchTokensProvider(id, tokens)
}

export function editorLanguageId(languageId: string, monacoLanguageId: string): string {
  return registeredLanguageIds[languageId] ?? monacoLanguageId
}

const cppCliTypeKeywords = ['bool', 'char', 'char16_t', 'char32_t', 'double', 'float', 'int', 'long', 'short', 'signed', 'unsigned', 'void', 'wchar_t']

const cppRootRules = cppTokens.tokenizer.root ?? []
const [cppRawStringRule, , ...cppRulesAfterIdentifier] = cppRootRules

export const cppCliTokens: monaco.languages.IMonarchLanguage = {
  ...cppTokens,
  cppCliTypeKeywords,
  tokenizer: {
    ...cppTokens.tokenizer,
    root: [
      // The upstream raw-string rule must run before any identifier rule so R/u8R/LR prefixes
      // enter the delimiter-aware raw-string state instead of being consumed as identifiers.
      ...(cppRawStringRule ? [cppRawStringRule] : []),
      [/(using)(\s+)(namespace)(\s+)([A-Za-z_]\w*(?:(?:::|\.)[A-Za-z_]\w*)*)/, ['keyword', 'white', 'keyword', 'white', 'namespace']],
      [/[A-Za-z_]\w*(?:::[A-Za-z_]\w*)+(?=\s*\()/, 'function'],
      [/([A-Z][A-Za-z0-9_]*)(\^)/, ['type.identifier', 'variable']],
      [/(>)(\^)/, ['delimiter.angle', 'variable']],
      [/[A-Z][A-Za-z0-9_]*/, 'type.identifier'],
      [
        /[A-Za-z_]\w*(?=\s*\()/,
        {
          cases: {
            '@cppCliTypeKeywords': 'type.identifier',
            '@keywords': { token: 'keyword.$0' },
            '@default': 'function',
          },
        },
      ],
      [
        /[A-Za-z_]\w*/,
        {
          cases: {
            '@cppCliTypeKeywords': 'type.identifier',
            '@keywords': { token: 'keyword.$0' },
            '@default': 'identifier',
          },
        },
      ],
      ...cppRulesAfterIdentifier,
    ],
  },
}

const assemblyConfiguration: monaco.languages.LanguageConfiguration = {
  comments: { lineComment: ';' },
  brackets: [
    ['[', ']'],
    ['(', ')'],
  ],
  wordPattern: /(?:[A-Za-z_.][\w.]*)/,
}

export const assemblyTokens: monaco.languages.IMonarchLanguage = {
  defaultToken: 'identifier',
  tokenPostfix: '.asm',
  tokenizer: {
    root: [
      [/^(\s*)(G_M\w+)(:)/, ['white', 'label', 'delimiter']],
      [/^([^;\s].*:)\s*$/, 'function'],
      [/^(\s*)([A-Za-z][\w.]*)/, ['white', 'keyword']],
      [/[;#].*$/, 'comment'],
      [/\b(?:byte|word|dword|qword|xmmword|ymmword|zmmword|ptr|short|near|far)\b/i, 'keyword'],
      [/%?(?:r(?:1[0-5]|[0-9])(?:[dwb])?|[re]?(?:ax|bx|cx|dx|si|di|sp|bp)|[abcd][lh]|rip|eip|xmm\d+|ymm\d+|zmm\d+|k\d+)\b/i, 'variable'],
      [/\b(?:0x[0-9a-f]+|\d+)\b/i, 'number'],
      [/\bG_M\w+\b/i, 'label'],
      [/\b[A-Za-z_.$?][\w.$?]*(?=\s*(?:\(|$))/, 'function'],
      [/[[\](),:+*-]/, 'delimiter'],
      [/[ \t\r\n]+/, 'white'],
    ],
  },
}

const minilangConfiguration: monaco.languages.LanguageConfiguration = {
  wordPattern: /[A-Za-z_]\w*/,
  autoClosingPairs: [{ open: '"', close: '"', notIn: ['string'] }],
  surroundingPairs: [{ open: '"', close: '"' }],
}

const javascriptConfiguration: monaco.languages.LanguageConfiguration = {
  comments: { lineComment: '//', blockComment: ['/*', '*/'] },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"', notIn: ['string', 'comment'] },
    { open: "'", close: "'", notIn: ['string', 'comment'] },
  ],
}

export const javascriptTokens: monaco.languages.IMonarchLanguage = {
  defaultToken: 'identifier',
  tokenPostfix: '.javascript',
  keywords: [
    'as',
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'export',
    'extends',
    'false',
    'finally',
    'for',
    'from',
    'function',
    'get',
    'if',
    'import',
    'in',
    'instanceof',
    'let',
    'new',
    'null',
    'of',
    'return',
    'set',
    'static',
    'super',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'var',
    'void',
    'while',
    'with',
    'yield',
  ],
  tokenizer: {
    root: [
      { include: '@whitespace' },
      [/[A-Za-z_$][\w$]*(?=\s*\()/, { cases: { '@keywords': 'keyword', '@default': 'function' } }],
      [/[A-Za-z_$][\w$]*(?=\s*:)/, 'property'],
      [/[A-Za-z_$][\w$]*/, { cases: { '@keywords': 'keyword', '@default': 'identifier' } }],
      [/(?:0[xX][0-9a-fA-F]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)/, 'number'],
      [/"/, { token: 'string.quote', next: '@doubleQuotedString' }],
      [/'/, { token: 'string.quote', next: '@singleQuotedString' }],
      [/[{}()[\]]/, '@brackets'],
      [/[;,.]/, 'delimiter'],
      [/[=><!~?:&|+\-*/%^]+/, 'operator'],
    ],
    whitespace: [
      [/[ \t\r\n]+/, 'white'],
      [/\/\*/, 'comment', '@comment'],
      [/\/\/.*$/, 'comment'],
    ],
    comment: [
      [/[^/*]+/, 'comment'],
      [/\*\//, 'comment', '@pop'],
      [/[/*]/, 'comment'],
    ],
    doubleQuotedString: [
      [/[^\\"]+/, 'string'],
      [/\\./, 'string.escape'],
      [/"/, { token: 'string.quote', next: '@pop' }],
    ],
    singleQuotedString: [
      [/[^\\']+/, 'string'],
      [/\\./, 'string.escape'],
      [/'/, { token: 'string.quote', next: '@pop' }],
    ],
  },
}

const minilangTokens: monaco.languages.IMonarchLanguage = {
  defaultToken: 'identifier',
  tokenPostfix: '.minilang',
  tokenizer: {
    root: [
      [/[ \t\r\n]+/, 'white'],
      [/\bprint\b/, 'keyword'],
      [/"/, { token: 'string.quote', next: '@string' }],
      [/[A-Za-z_]\w*/, 'identifier'],
    ],
    string: [
      [/[^\\"]+/, 'string'],
      [/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/"/, { token: 'string.quote', next: '@pop' }],
    ],
  },
}

const gsharpConfiguration: monaco.languages.LanguageConfiguration = {
  comments: { lineComment: '//', blockComment: ['/*', '*/'] },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"', notIn: ['string', 'comment'] },
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
  ],
}

const gsharpTokens: monaco.languages.IMonarchLanguage = {
  defaultToken: '',
  tokenPostfix: '.gsharp',
  symbols: /[=><!~?:&|+\-*/%^]+/,
  keywords: [
    'package',
    'import',
    'func',
    'let',
    'var',
    'const',
    'class',
    'struct',
    'interface',
    'data',
    'object',
    'enum',
    'extension',
    'if',
    'else',
    'guard',
    'for',
    'in',
    'while',
    'match',
    'case',
    'return',
    'break',
    'continue',
    'throw',
    'try',
    'catch',
    'finally',
    'defer',
    'scope',
    'async',
    'await',
    'public',
    'private',
    'protected',
    'internal',
    'shared',
    'static',
    'virtual',
    'override',
    'partial',
    'nil',
    'true',
    'false',
  ],
  tokenizer: {
    root: [
      [/(func)(\s+)([A-Za-z_]\w*)/, ['keyword', 'white', 'function']],
      [/(class|struct|interface|data|object|enum|extension)(\s+)([A-Za-z_]\w*)/, ['keyword', 'white', 'type.identifier']],
      [/[A-Za-z_]\w*(?=\s*\()/, 'function'],
      [/[A-Z][A-Za-z0-9_]*/, 'type.identifier'],
      [/[A-Za-z_]\w*/, { cases: { '@keywords': 'keyword', '@default': 'identifier' } }],
      { include: '@whitespace' },
      [/\d+(?:\.\d+)?/, 'number'],
      [/"/, { token: 'string.quote', next: '@string' }],
      [/[{}()[\]]/, '@brackets'],
      [/[<>](?!@symbols)/, '@brackets'],
      [/@symbols/, 'operator'],
      [/[;,.]/, 'delimiter'],
    ],
    whitespace: [
      [/[ \t\r\n]+/, 'white'],
      [/\/\*/, 'comment', '@comment'],
      [/\/\/.*$/, 'comment'],
    ],
    comment: [
      [/[^/*]+/, 'comment'],
      [/\*\//, 'comment', '@pop'],
      [/[/*]/, 'comment'],
    ],
    string: [
      [/[^\\"]+/, 'string'],
      [/\\./, 'string.escape'],
      [/"/, { token: 'string.quote', next: '@pop' }],
    ],
  },
}

const ilConfiguration: monaco.languages.LanguageConfiguration = {
  comments: { lineComment: '//', blockComment: ['/*', '*/'] },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"', notIn: ['string', 'comment'] },
    { open: "'", close: "'", notIn: ['string', 'comment'] },
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
}

export const ilTokens: monaco.languages.IMonarchLanguage = {
  defaultToken: 'identifier',
  tokenPostfix: '.il',
  symbols: /[=><!~?:&|+\-*/%^]+/,
  keywords: [
    ...ilKeywords,
    'abstract',
    'ansi',
    'assembly',
    'auto',
    'beforefieldinit',
    'catch',
    'cil',
    'class',
    'explicit',
    'extends',
    'famandassem',
    'family',
    'famorassem',
    'fault',
    'field',
    'filter',
    'final',
    'finally',
    'forwarder',
    'hidebysig',
    'implements',
    'init',
    'instance',
    'interface',
    'internalcall',
    'literal',
    'managed',
    'marshal',
    'method',
    'modopt',
    'modreq',
    'native',
    'nested',
    'newslot',
    'noinlining',
    'nooptimization',
    'notserialized',
    'pinvokeimpl',
    'pinned',
    'private',
    'privatescope',
    'public',
    'request',
    'rtspecialname',
    'runtime',
    'sealed',
    'sequential',
    'serializable',
    'specialname',
    'static',
    'synchronized',
    'to',
    'unmanaged',
    'value',
    'valuetype',
    'virtual',
  ],
  primitiveTypes: [...ilPrimitiveTypes, 'bool', 'char', 'float32', 'float64', 'int8', 'int16', 'int32', 'int64', 'native int', 'native uint', 'object', 'string', 'typedref', 'uint8', 'uint16', 'uint32', 'uint64', 'void'],
  opcodes: [
    ...ilOpcodes,
    'add',
    'add.ovf',
    'add.ovf.un',
    'and',
    'arglist',
    'beq',
    'beq.s',
    'bge',
    'bge.s',
    'bge.un',
    'bge.un.s',
    'bgt',
    'bgt.s',
    'bgt.un',
    'bgt.un.s',
    'ble',
    'ble.s',
    'ble.un',
    'ble.un.s',
    'blt',
    'blt.s',
    'blt.un',
    'blt.un.s',
    'bne.un',
    'bne.un.s',
    'box',
    'br',
    'br.s',
    'break',
    'brfalse',
    'brfalse.s',
    'brtrue',
    'brtrue.s',
    'call',
    'calli',
    'callvirt',
    'castclass',
    'ceq',
    'cgt',
    'cgt.un',
    'ckfinite',
    'clt',
    'clt.un',
    'constrained.',
    'conv.i',
    'conv.i1',
    'conv.i2',
    'conv.i4',
    'conv.i8',
    'conv.ovf.i',
    'conv.ovf.i.un',
    'conv.ovf.i1',
    'conv.ovf.i1.un',
    'conv.ovf.i2',
    'conv.ovf.i2.un',
    'conv.ovf.i4',
    'conv.ovf.i4.un',
    'conv.ovf.i8',
    'conv.ovf.i8.un',
    'conv.ovf.u',
    'conv.ovf.u.un',
    'conv.ovf.u1',
    'conv.ovf.u1.un',
    'conv.ovf.u2',
    'conv.ovf.u2.un',
    'conv.ovf.u4',
    'conv.ovf.u4.un',
    'conv.ovf.u8',
    'conv.ovf.u8.un',
    'conv.r.un',
    'conv.r4',
    'conv.r8',
    'conv.u',
    'conv.u1',
    'conv.u2',
    'conv.u4',
    'conv.u8',
    'cpblk',
    'cpobj',
    'div',
    'div.un',
    'dup',
    'endfilter',
    'endfinally',
    'initblk',
    'initobj',
    'isinst',
    'jmp',
    'ldarg',
    'ldarg.0',
    'ldarg.1',
    'ldarg.2',
    'ldarg.3',
    'ldarg.s',
    'ldarga',
    'ldarga.s',
    'ldc.i4',
    'ldc.i4.0',
    'ldc.i4.1',
    'ldc.i4.2',
    'ldc.i4.3',
    'ldc.i4.4',
    'ldc.i4.5',
    'ldc.i4.6',
    'ldc.i4.7',
    'ldc.i4.8',
    'ldc.i4.m1',
    'ldc.i4.s',
    'ldc.i8',
    'ldc.r4',
    'ldc.r8',
    'ldelem',
    'ldelem.i',
    'ldelem.i1',
    'ldelem.i2',
    'ldelem.i4',
    'ldelem.i8',
    'ldelem.r4',
    'ldelem.r8',
    'ldelem.ref',
    'ldelem.u1',
    'ldelem.u2',
    'ldelem.u4',
    'ldelema',
    'ldfld',
    'ldflda',
    'ldftn',
    'ldind.i',
    'ldind.i1',
    'ldind.i2',
    'ldind.i4',
    'ldind.i8',
    'ldind.r4',
    'ldind.r8',
    'ldind.ref',
    'ldind.u1',
    'ldind.u2',
    'ldind.u4',
    'ldlen',
    'ldloc',
    'ldloc.0',
    'ldloc.1',
    'ldloc.2',
    'ldloc.3',
    'ldloc.s',
    'ldloca',
    'ldloca.s',
    'ldnull',
    'ldobj',
    'ldsfld',
    'ldsflda',
    'ldstr',
    'ldtoken',
    'ldvirtftn',
    'leave',
    'leave.s',
    'localloc',
    'mkrefany',
    'mul',
    'mul.ovf',
    'mul.ovf.un',
    'neg',
    'newarr',
    'newobj',
    'no.',
    'nop',
    'not',
    'or',
    'pop',
    'readonly.',
    'refanytype',
    'refanyval',
    'rem',
    'rem.un',
    'ret',
    'rethrow',
    'shl',
    'shr',
    'shr.un',
    'sizeof',
    'starg',
    'starg.s',
    'stelem',
    'stelem.i',
    'stelem.i1',
    'stelem.i2',
    'stelem.i4',
    'stelem.i8',
    'stelem.r4',
    'stelem.r8',
    'stelem.ref',
    'stfld',
    'stind.i',
    'stind.i1',
    'stind.i2',
    'stind.i4',
    'stind.i8',
    'stind.r4',
    'stind.r8',
    'stind.ref',
    'stloc',
    'stloc.0',
    'stloc.1',
    'stloc.2',
    'stloc.3',
    'stloc.s',
    'stobj',
    'stsfld',
    'sub',
    'sub.ovf',
    'sub.ovf.un',
    'switch',
    'tail.',
    'throw',
    'unaligned.',
    'unbox',
    'unbox.any',
    'volatile.',
    'xor',
  ],
  tokenizer: {
    root: [
      [/^(\s*)([A-Za-z_][\w.$]*)(:(?!:))/, ['white', 'label', 'delimiter']],
      { include: '@whitespace' },
      [/^(\s*)(\.assembly)(\s+)(extern)(\s+)([^\s{]+)/, ['white', 'keyword', 'white', 'keyword', 'white', 'macro']],
      [/^(\s*)(\.assembly)(\s+)([^\s{]+)/, ['white', 'keyword', 'white', 'macro']],
      [/(\[)((?!(?:in|out|opt|retval)\])[^\]\r\n]+)(\])(?=[A-Za-z_'<])/, ['delimiter', 'macro', 'delimiter']],
      [ilStandaloneAssemblyIdentityPattern, ['white', 'delimiter', 'macro']],
      [/([A-Za-z_][\w.`]*(?:\.[A-Za-z_][\w.`]*)*)(::)(\.[A-Za-z_][\w.]*)/, ['type.identifier', 'delimiter', 'keyword']],
      [/([A-Za-z_][\w.`]*(?:\.[A-Za-z_][\w.`]*)*)(::)([A-Za-z_.$<>][\w.$<>`]*)/, ['type.identifier', 'delimiter', 'function']],
      [/\.[A-Za-z_][\w.]*/, 'keyword'],
      [/"/, { token: 'string.quote', next: '@string' }],
      [/'/, { token: 'string.quote', next: '@quotedIdentifier' }],
      [/[+-]?(?:0x[0-9a-f]+|\d+(?:\.\d+)?(?:e[+-]?\d+)?)/, 'number'],
      [/[A-Z][A-Za-z0-9_`]*(?:\.[A-Z][A-Za-z0-9_`]*)+/, 'type.identifier'],
      [
        /[A-Za-z_<>$][\w<>$'.]*/,
        {
          cases: {
            '@opcodes': 'keyword',
            '@keywords': 'keyword',
            '@primitiveTypes': 'keyword',
            '@default': 'identifier',
          },
        },
      ],
      [/[{}()[\]]/, '@brackets'],
      [/[,:;]/, 'delimiter'],
      [/@symbols/, 'operator'],
    ],
    whitespace: [
      [/[ \t\r\n]+/, 'white'],
      [/\/\*/, 'comment', '@comment'],
      [/\/\/.*$/, 'comment'],
    ],
    comment: [
      [/[^/*]+/, 'comment'],
      [/\*\//, 'comment', '@pop'],
      [/[/*]/, 'comment'],
    ],
    string: [
      [/[^\\"]+/, 'string'],
      [/\\./, 'string.escape'],
      [/"/, { token: 'string.quote', next: '@pop' }],
    ],
    quotedIdentifier: [
      [/[^\\']+/, 'string'],
      [/\\./, 'string.escape'],
      [/'/, { token: 'string.quote', next: '@pop' }],
    ],
  },
}
