<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\ArtifactStore\SharpLabNext.ArtifactStore.Client\SharpLabNext.ArtifactStore.Client.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\SharpLabNext.Observability\SharpLabNext.Observability.csproj" />
    <ProjectReference Include="..\..\..\RuntimeApi\SharpLabNext.Runtime\SharpLabNext.Runtime.csproj" />
    <ProjectReference Include="..\..\..\WorkerHost\SharpLabNext.WorkerHost\SharpLabNext.WorkerHost.csproj" />
    <ProjectReference Include="..\SharpLabNext.Worker.Artifacts.Default.Processor\SharpLabNext.Worker.Artifacts.Default.Processor.csproj" />
    <ProjectReference Include="..\SharpLabNext.Worker.Artifacts.Default.Protocol\SharpLabNext.Worker.Artifacts.Default.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SharpLabNext.Worker.Artifacts.Default.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Infrastructure\PascalCaseQuery.cs"
             Link="Infrastructure\PascalCaseQuery.cs" />
  </ItemGroup>

</Project>
