<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeFrameworkVersion>5.0.17</RuntimeFrameworkVersion>
    <RollForward>Major</RollForward>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SharpLabNext.UnitTests" />
  </ItemGroup>

</Project>
