<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\SharpLabNext.Observability\SharpLabNext.Observability.csproj" />
    <ProjectReference Include="..\SharpLabNext.Worker.Artifacts.ILAssembler\SharpLabNext.Worker.Artifacts.ILAssembler.csproj" Aliases="global,ArtifactAssemblerHost" />
    <ProjectReference Include="..\..\..\ArtifactStore\SharpLabNext.ArtifactStore\SharpLabNext.ArtifactStore.csproj" Aliases="ArtifactStoreHost" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SharpLabNext.Worker.Artifacts.ILAssembler\artifact-worker.json"
          Link="artifact-worker.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
