<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SharpLabNext.RuntimeProtocol\SharpLabNext.RuntimeProtocol.csproj" />
    <ProjectReference Include="..\..\Contracts\SharpLabNext.Artifacts.Contracts\SharpLabNext.Artifacts.Contracts.csproj" />
    <ProjectReference Include="..\..\RuntimeApi\SharpLabNext.Runtime\SharpLabNext.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SharpLabNext.IntegrationTests" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
