import type { CatalogDocument } from '../api/types'

export function createCatalogFixture(): CatalogDocument {
  return {
    schemaVersion: 1,
    revision: 'test-catalog-1',
    releaseId: 'test-release',
    languages: [
      {
        id: 'csharp',
        displayName: 'C#',
        monacoLanguageId: 'csharp',
        extensions: ['.cs'],
        defaultFileName: 'Program.cs',
        defaultSource: 'Console.WriteLine("C#");\n',
        defaultToolchainId: 'roslyn-stable',
        capabilities: ['ast', 'explain'],
        legacyAliases: ['cs'],
      },
      {
        id: 'fsharp',
        displayName: 'F#',
        monacoLanguageId: 'fsharp',
        extensions: ['.fs'],
        defaultFileName: 'Program.fs',
        defaultSource: 'printfn "F#"\n',
        defaultToolchainId: 'fsharp-stable',
        capabilities: ['ast', 'multi-file', 'source-order'],
        legacyAliases: ['fs'],
      },
    ],
    toolchains: [
      {
        id: 'roslyn-stable',
        displayName: 'Roslyn Stable',
        workerId: 'roslyn-stable',
        releaseTrack: 'stable',
        resolvedVersion: '5.6.0',
        defaultReferenceSetId: 'net10-ref',
        supportedLanguageIds: ['csharp'],
        allowedReferenceSetIds: ['net10-ref', 'net11-ref'],
        producesArtifactFormats: ['dotnet-managed-pe-v1'],
        capabilities: ['compile-check', 'managed-pe', 'ast', 'explain'],
        metadataFeatureTags: [],
        legacyAliases: [],
        availability: {
          installed: true,
          health: 'skeleton',
          reason: 'Fake worker only.',
        },
      },
      {
        id: 'fsharp-stable',
        displayName: 'F# Stable',
        workerId: 'fsharp-stable',
        releaseTrack: 'stable',
        resolvedVersion: '43.12.204',
        defaultReferenceSetId: 'net10-ref',
        supportedLanguageIds: ['fsharp'],
        allowedReferenceSetIds: ['net10-ref'],
        producesArtifactFormats: ['dotnet-managed-pe-v1'],
        capabilities: ['compile-check', 'managed-pe', 'ast'],
        metadataFeatureTags: [],
        legacyAliases: [],
        availability: {
          installed: false,
          health: 'not-built',
          reason: 'Not built.',
        },
      },
    ],
    referenceSets: [
      {
        id: 'net10-ref',
        displayName: '.NET 10',
        targetFramework: 'net10.0',
        digest: 'net10',
        runtimeFamily: 'coreclr',
        requiredRuntimeFeatureTags: [],
        metadataFeatureTags: [],
        availability: { installed: true, health: 'healthy' },
      },
      {
        id: 'net11-ref',
        displayName: '.NET Main',
        targetFramework: 'net11.0',
        digest: 'net11',
        runtimeFamily: 'coreclr',
        requiredRuntimeFeatureTags: ['runtime.dotnet-11'],
        metadataFeatureTags: [],
        availability: {
          installed: false,
          health: 'not-built',
          reason: 'Not built.',
        },
      },
    ],
    runtimes: [
      {
        id: 'dotnet-10-linux-x64',
        displayName: '.NET 10',
        family: 'coreclr',
        resolvedVersion: '10.0.9',
        rid: 'linux-x64',
        architecture: 'x64',
        acceptedArtifactFormats: ['dotnet-managed-pe-v1'],
        capabilities: ['run', 'jit-asm'],
        providedRuntimeFeatureTags: [],
        providedMetadataFeatureTags: [],
        legacyAliases: [],
        availability: {
          installed: false,
          health: 'not-built',
          reason: 'Not built.',
        },
      },
      {
        id: 'dotnet-11-linux-x64',
        displayName: '.NET Main',
        family: 'coreclr',
        resolvedVersion: '11.0.0-preview',
        rid: 'linux-x64',
        architecture: 'x64',
        acceptedArtifactFormats: ['dotnet-managed-pe-v1'],
        capabilities: ['run', 'jit-asm'],
        providedRuntimeFeatureTags: ['runtime.dotnet-11'],
        providedMetadataFeatureTags: [],
        legacyAliases: [],
        availability: {
          installed: false,
          health: 'not-built',
          reason: 'Not built.',
        },
      },
    ],
    artifactProcessors: [
      {
        id: 'artifacts-default',
        displayName: 'Artifacts',
        resolvedVersion: '1.0.0',
        workerId: 'artifacts-default',
        acceptsArtifactFormats: ['dotnet-managed-pe-v1'],
        producesArtifactFormats: ['il-text-v1', 'decompiled-csharp-v1'],
        capabilities: ['il', 'decompiled-csharp'],
        transformations: [],
        acceptedMetadataFeatureTags: [],
        availability: {
          installed: false,
          health: 'not-built',
          reason: 'Not built.',
        },
      },
    ],
    outputs: [
      {
        id: 'compile-check',
        displayName: 'Compile Check',
        renderer: 'diagnostics',
        requiresRuntime: false,
        requiredCapabilities: ['compile-check'],
        acceptedArtifactFormats: [],
      },
      {
        id: 'ast',
        displayName: 'AST',
        renderer: 'ast-tree',
        requiresRuntime: false,
        requiredCapabilities: ['ast'],
        acceptedArtifactFormats: [],
      },
      {
        id: 'il',
        displayName: 'IL',
        renderer: 'il',
        requiresRuntime: false,
        requiredCapabilities: ['managed-pe', 'il'],
        acceptedArtifactFormats: ['dotnet-managed-pe-v1'],
      },
      {
        id: 'decompiled-csharp',
        displayName: 'Decompiled C#',
        renderer: 'csharp',
        requiresRuntime: false,
        requiredCapabilities: ['managed-pe', 'decompiled-csharp'],
        acceptedArtifactFormats: ['dotnet-managed-pe-v1'],
      },
      {
        id: 'run',
        displayName: 'Run',
        renderer: 'runtime-output',
        requiresRuntime: true,
        requiredCapabilities: ['managed-pe', 'run'],
        acceptedArtifactFormats: ['dotnet-managed-pe-v1'],
      },
      {
        id: 'explain',
        displayName: 'Explain',
        renderer: 'explain',
        requiresRuntime: false,
        requiredCapabilities: ['explain'],
        acceptedArtifactFormats: [],
      },
    ],
    compatibility: [
      {
        id: 'roslyn-net10',
        kind: 'toolchain-reference-set',
        fromId: 'roslyn-stable',
        toId: 'net10-ref',
        allowed: true,
        requiredMetadataFeatureTags: [],
      },
      {
        id: 'roslyn-net11',
        kind: 'toolchain-reference-set',
        fromId: 'roslyn-stable',
        toId: 'net11-ref',
        allowed: true,
        requiredMetadataFeatureTags: [],
      },
      {
        id: 'fsharp-net10',
        kind: 'toolchain-reference-set',
        fromId: 'fsharp-stable',
        toId: 'net10-ref',
        allowed: true,
        requiredMetadataFeatureTags: [],
      },
      {
        id: 'managed-artifacts',
        kind: 'artifact-processor',
        fromId: 'dotnet-managed-pe-v1',
        toId: 'artifacts-default',
        allowed: true,
        requiredMetadataFeatureTags: [],
      },
      {
        id: 'managed-net10',
        kind: 'artifact-runtime',
        fromId: 'dotnet-managed-pe-v1',
        toId: 'dotnet-10-linux-x64',
        allowed: true,
        requiredMetadataFeatureTags: [],
      },
      {
        id: 'managed-net11',
        kind: 'artifact-runtime',
        fromId: 'dotnet-managed-pe-v1',
        toId: 'dotnet-11-linux-x64',
        allowed: true,
        requiredMetadataFeatureTags: [],
      },
    ],
    presets: [
      {
        id: 'csharp-stable-net10',
        displayName: 'C# / Stable / .NET 10',
        languageId: 'csharp',
        toolchainId: 'roslyn-stable',
        referenceSetId: 'net10-ref',
        defaultOutputId: 'decompiled-csharp',
        defaultRuntimeId: 'dotnet-10-linux-x64',
        legacyAliases: ['main'],
        availability: { installed: true, health: 'healthy' },
      },
    ],
  }
}
