<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpLabNext.Worker.Artifacts.JSIL\SharpLabNext.Worker.Artifacts.JSIL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SharpLabNext.Worker.Artifacts.JSIL\artifact-worker.json"
          Link="artifact-worker.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
